name: furniture_shop_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  flutter_animate: ^4.2.0+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.3
  get_it: ^7.6.4
  intl: ^0.18.1
  talker_bloc_logger: ^2.2.1
  async: ^2.11.0
  cached_network_image: ^3.3.0
  path_provider: ^2.1.1
  talker: ^3.1.4
  sqflite: ^2.3.0
  path: ^1.8.3
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.2
  flash: ^3.1.0
  loader_overlay: ^3.0.0
  talker_dio_logger: ^2.3.1
  go_router: ^12.1.1
  firebase_database: ^10.3.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Gelasio
      fonts:
        - asset: assets/fonts/Gelasio/Gelasio-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gelasio/Gelasio-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gelasio/Gelasio-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gelasio/Gelasio-Bold.ttf
          weight: 700
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
          weight: 400
        - asset: assets/fonts/Merriweather/Merriweather-Bold.ttf
          weight: 700
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/Nunito Sans/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito Sans/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito Sans/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito Sans/NunitoSans-Bold.ttf
          weight: 700