name: furniture_shop_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-87.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  flutter_animate: ^4.2.0+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Gelasio
      fonts:
        - asset: assets/fonts/Gelasio/Gelasio-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gelasio/Gelasio-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gelasio/Gelasio-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gelasio/Gelasio-Bold.ttf
          weight: 700
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
          weight: 400
        - asset: assets/fonts/Merriweather/Merriweather-Bold.ttf
          weight: 700